<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Subsystem>console</Subsystem>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="info\code.txt" />
    <None Remove="info\colorcodes.txt" />
    <None Remove="info\DQB2_2.ttf" />
    <None Remove="info\IW4RD3.ttf" />
    <None Remove="info\PRGothIWA-HW-Dm.ttf" />
    <None Remove="Info\versions\Steam-DEBUG-1.7.2_1.7.3a.txt" />
    <None Remove="Info\versions\Steam1.7.2_1.7.3d.txt" />
    <None Remove="Info\versions\Switch-Demo-EU-1.0-JumboDemo-EU-1.1.txt" />
    <None Remove="Info\versions\Switch-Demo-EU-1.0.txt" />
    <None Remove="Info\versions\Switch-JumboDemo-EU-1.1.txt" />
    <None Remove="Info\versions\Switch-JumboDemo-JP-1.1.txt" />
    <None Remove="Info\versions\Switch-Release-EU-1.5.2.txt" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="info\code.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Info\versions\Steam1.7.2_1.7.3d.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Info\versions\Switch-Demo-EU-1.0-JumboDemo-EU-1.1.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Info\versions\Switch-JumboDemo-JP-1.1.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Info\versions\Switch-Release-EU-1.5.2.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="info\colorcodes.txt" />
    <Resource Include="info\DQB2_2.ttf" />
    <Resource Include="info\PRGothIWA-HW-Dm.ttf" />
  </ItemGroup>
</Project>
